### PR TITLE
fix(fusionreport) set html as optional

### PR DESCRIPTION
**Pull request by fevac**
Part of: https://github.com/nf-core/rnafusion/issues/376

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnafusion/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/rnafusion _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by rannick — APPROVED** [review]

**Comment by fevac** [comment]
@rannick as we thought the error propagates and fails in `fusioninspector`

With error message:
`No fusions listed in input file: <case_id>.fusionreport.tsv, exiting gracefully.` 

Looking into it

**Comment by fevac** [comment]
Actually I'm not sure how we want to handle this, if empty files or handling the error. Let's talk tomorrow

**Comment by rannick** [comment]
I would limit the change to fusionreport and implement a logical gate in case fusionreport output is empty in another PR, i.e. keep fusioninspector unchanged. Does that make sense to you?

**Comment by fevac** [comment]
> Hi @fevac - I'm interested to hear how you are getting on with this fix as the same issue is currently preventing me from using this workflow - is there anything I can work with you on?

The plan is to do what @rannick suggested above: so implementing a logical switch in a different PR. I have not started yet so feel free to start if you have the time. Not sure if @rannick might have time or has been looking into it

**Comment by rannick** [comment]
@efgstone @fevac yes, I am looking into it. Currently working on merging the template 2.9, which turned out more tricky than anticipated but that is right next for me. Expect an at least partial patch (no fusion-report reference fix) mid-next week I would say

**Pull request merged**
