### PR TITLE
fix: using official STAR-Fusion container

### PR DESCRIPTION
**Pull request by matq007**
# nf-core/rnafusion pull request

Many thanks for contributing to nf-core/rnafusion!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/rnafusion branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/rnafusion)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/rnafusion/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by t-neumann** [comment]
I will try it with this, but I'm pretty sure I used the actual FusionInspector container here `trinityctat/fusioninspector:tag`

**Comment by matq007** [comment]
It shouldn't matter, `STAR-Fusion` container comes with all tools from building to visualization. So we are saving space on the user side.

**Comment by t-neumann** [comment]
Nice - it works :)

**Review by t-neumann — APPROVED** [review]
Tried it with the container and indeed it works - so go from my side.

**Pull request merged**
