### PR TITLE
Implemented custom summary report with some rich visualization

### PR DESCRIPTION
**Pull request by matq007**
Example images of the summary report. Additional suggestions will be implemented after feedback from KI.

### Dabshoard
screencapture-file-users-mproksik-school-sdu-thesis-code-results-report-index-html-2018-12-08-16_46_32

### Fusion page
screencapture-file-users-mproksik-school-sdu-thesis-code-results-report-brd4_nutm1-html-2018-12-08-16_46_57

### CODE REVIEW

**Comment by ewels** [comment]
Love it 👍 Could you attach a HTML file for us to play with too please?

**Comment by matq007** [comment]
> Love it 👍 Could you attach a HTML file for us to play with too please?

Here you go [example-compressed.zip](https://github.com/nf-core/rnafusion/files/2659848/example-compressed.zip)
There are quite a lot of js and css there but this can be trimmed down a little once we decide on the final visualization. The tool is also capable of additional customization defined in [example_config.yml](https://github.com/nf-core/rnafusion/blob/2f409d576748a91da5b39c1d9a51873cb818f14e/bin/summary/example_config.yml)

**Comment by mtstahl** [comment]
Looks really cool! It would be great to also see which fusions have been found in which samples.

**Comment by matq007** [comment]
> Looks really cool! It would be great to also see which fusions have been found in which samples.

Well, you have to run the pipeline per sample. This means that for each sample (paired-end) you get a summary report like this.

**Comment by ewels** [comment]
Super nice! As there are multiple HTML files per sample, maybe just naming the folder with the sample name would be good. How much of the file size is library and how much is data? Would be nicer if we could squeeze everything into a single HTML file, but I don't know if that would make it a ridiculous size.

Some rapid thoughts from a quick look:

* Summary page
    * Tool detection plot: Would be nice to know how many of the hits are shared here. Looks like HighCharts should support venn diagrams [any day now](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/878283-venn-diagram)
  * Table: True / False would be nicer as colour coded [badges](http://getbootstrap.com/docs/4.1/components/badge/)
  * Table: I always think the default of 10 visible rows is too few. Maybe default to 50 instead?
  * Can we have a little more metadata at the top explaining how the report was generated?
* Fusion page
  * More `code` blocks would be nice in the table for easier reading
  * Badges to for the type categories also helps with reading
  * Some leader text above each section explaining what the data is, approximately how it's generated and how to interpret it goes a long way.
* Scilifelab > SciLifeLab. Love that you went to the trouble of using a SVG for the heart logo - maybe make it black or grey though so it doesn't stand out _quite_ so much? 😉 

Looks seriously amazing though, you've done a brilliant job here 👍 

Phil

**Comment by ewels** [comment]
https://www.highcharts.com/demo/venn-diagram 🎉 ✨ 

image

**Comment by matq007** [comment]
- [ ] Venn diagram not implemented. Unreadable for 3+ tools.
- [ ] Missing metadata and description in the report (implemented in the code) 
- [x] Badges included for categories in table
- [x] Table content wrapped inside `<code>`
- [x] Renamed Scilifelab to SciLifeLab and added hyperlink
screencapture-file-users-mproksik-desktop-kremes-etv6_ntrk3-html-2018-12-13-23_16_06
screencapture-file-users-mproksik-desktop-kremes-index-html-2018-12-13-23_15_00

**Comment by ewels** [comment]
Looking awesome 😍 Down to the really minor things now:

* Can the "Tools hit" values have a background bar like in MultiQC tables? (Not sure if this is possible with DataTables).
* In the network graph, could the fusion gene blob have a different colour?
* Could the three graphs use different colour schemes? Makes it faster to interpret.
  * The new one on the right could use a sequential / intensity scheme to indicate that higher numbers are better. eg. [ColorBrewer](http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3) BuGn or something.
* A bit of descriptive text for each section would still be fab 👍

**Comment by apeltzer** [comment]
Awesome is not enough for this PR - amazing work!

**Comment by matq007** [comment]
- [x] Tool hit value changed to a progress bar
- [x] Network graph done (maybe needs a whole rewrite to make the node positions hard coded)
- [x] All graphs are using a different color scheme, the last one has ColorBrewer 
Including [example.zip](https://github.com/nf-core/rnafusion/files/2686869/example.zip) files.

**Pull request merged**
