### PR TITLE
Make using COSMIC optional

### PR DESCRIPTION
**Pull request by rannick**
Closes https://github.com/nf-core/rnafusion/issues/514

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnafusion/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/rnafusion _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).

- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by nschcolnicov** [comment]
Thanks for this very much needed change. I tried testing these changes with:
nextflow run nf-core/rnafusion -r fusion_report_optional_cosmic -latest --input 'https://raw.githubusercontent.com/nf-core/test-datasets/rnafusion/testdata/human/samplesheet_valid.csv' --outdir results -profile docker

And it fails due to
```Could not find transcript <=> gene map file "Homo_sapiens.GRCh38.102.gtf"```

I think we need to set up igenomes first, since this value should be coming from there. Currently it comes from :

```gtf            = "${params.genomes_base}/ensembl/Homo_sapiens.${params.genome}.${params.ensembl_version}.gtf"```

But the params.genomes_base is set to:

```genomes_base               = "${params.outdir}/references"```

So the file is empty

**Comment by atrigila** [comment]
@nschcolnicov you need to add `--build-references`.

```
  nextflow run rnafusion -profile test,docker \
  -stub --build_references \
  --outdir results 
```

**Comment by nschcolnicov** [comment]
THank you @atrigila!
Running this works:
```nextflow run nf-core/rnafusion -r fusion_report_optional_cosmic -latest --input 'https://raw.githubusercontent.com/nf-core/test-datasets/rnafusion/testdata/human/samplesheet_valid.csv' --outdir results -profile docker --no_cosmic --build_references```

Maybe we should add into the pipeline handling or the docs that "--no_cosmic" must be used together with "--build_references" and it is not compatible with "--all"

**Review by atrigila — APPROVED** [review]
Looks good to me and it is going to be very useful when developing pipeline-level test cases.

**Comment by rannick** [comment]
> Thanks for this very much needed change. I tried testing these changes with: `nextflow run nf-core/rnafusion -r fusion_report_optional_cosmic -latest --input 'https://raw.githubusercontent.com/nf-core/test-datasets/rnafusion/testdata/human/samplesheet_valid.csv' --outdir results -profile docker --no_cosmic`
> 
> And it fails due to `Could not find transcript <=> gene map file "Homo_sapiens.GRCh38.102.gtf"`
> 
> I think we need to set up igenomes first, since this value should be coming from there. Currently it comes from :
> 
> `gtf = "${params.genomes_base}/ensembl/Homo_sapiens.${params.genome}.${params.ensembl_version}.gtf"`
> 
> But the params.genomes_base is set to:
> 
> `genomes_base = "${params.outdir}/references"`
> 
> So the file is empty.
> 
> Also tried running the branch wiht: `nextflow run nf-core/rnafusion -r fusion_report_optional_cosmic -latest --input 'https://raw.githubusercontent.com/nf-core/test-datasets/rnafusion/testdata/human/samplesheet_valid.csv' --outdir results -profile docker --no_cosmic` And I get the error: `Not a valid path value: 'results/references/fusioncatcher/human_v102'`
> 
> Which is due to missing reference files. Particularly the fusioncatcher_ref.
> 
> Should we add a special handling to avoid the user from using --all with --no_cosmic?

I think the problem you are seeing this is from not running `--build_references ` first before running the analysis, but does not have to do with the `--all` flag. I will solve this issue in https://github.com/nf-core/rnafusion/pull/505

**Pull request merged**
