### PR TITLE
Fixed #15

### LINKED ISSUE #15: Make pipeline pass Travis CI
Currently broken:
- [x] `nf-core lint`
- [x] tests

### PR DESCRIPTION
**Pull request by matq007**
The lint is passing with a warning about newer versions of the packages. Don't want to update them yet. First we make this pipeline pass everything.

### CODE REVIEW

**Comment by matq007** [comment]
Any suggestions why the builds are failing?

**Comment by ewels** [comment]
It's because the pull-request is set against `master`. We have a line in the tests that makes them error immediately if this is the case - `master` should only ever have PRs coming from `dev`. This is because `master` should have the last stable release code in and be the default branch, and it's easy to accidentally have PRs against it.

I updated the base of this to `dev`, but I think you'll need to push a new commit (can just rebase the last one and force push) to properly trigger a new travis test.

**Comment by matq007** [comment]
Closing and making new PR from scratch

**Comment by ewels** [comment]
> Closing and making new PR from scratch

Why?

**Pull request closed without merging**
