### PR TITLE
Megafusion key error fix

### PR DESCRIPTION
**Pull request by efgstone**
## PR checklist

- [x ] This comment contains a description of changes (with reason).

### CODE REVIEW

**Comment by efgstone** [comment]
related to issue: https://github.com/nf-core/rnafusion/issues/366

**Comment by rannick** [comment]
How have you tested this fix?

**Comment by rannick** [comment]
Ah yeah, the cosmic secrets are not known if you are testing on a fork (sigh). @maxulysse @apeltzer do you know a possibility to fix this?

**Comment by efgstone** [comment]
Hi @rannick - I have tested the fix and it is working for cases where the KeyError: "['INFO', 'Sample'] not in index" error message was being displayed. It does not solve all issues relating to cases where no fusions are detected though.

**Comment by rannick** [comment]
Since we are in the case of a broken dev branch, I will force the merge here, also because CI would not pick an error anyways (stubs only). Let's keep in mind that there will be extra testing once the empty fusions PR is implemented

**Pull request merged**
